filebeat.inputs:
  - type: log
    paths:
      - /var/log/nginx/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: ${ELASTIC_USERNAME}
  password: ${ELASTIC_PASSWORD}
  #username: "elastic"
  #password: "changeme%"
setup.kibana:
  host: "kibana:5601"
